/**
 * Q&A Engager -- Q&Aサイトでの質問検索・回答投稿
 *
 * Reddit, Quora, Yahoo!知恵袋, 知乎(Zhihu)等で
 * 関連キーワードの質問を検索し、ブランドに自然に言及する
 * 有益な回答を投稿する。
 */

import type { Page } from "playwright";
import { getBrowserPool } from "../browser-pool.js";
import {
  startActivity,
  completeActivity,
  failActivity,
  addArtifact,
} from "../activity-logger.js";
import type { ChannelConfig, ChannelType } from "./channel-registry.js";
import type { PostResult } from "./social-poster.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface QAEngageParams {
  projectId: string;
  taskId: string;
  channel: ChannelConfig;
  keyword: string;
  brandName: string;
  answerContent: string; // pre-generated by Ollama
}

// ---------------------------------------------------------------------------
// Screenshot helper
// ---------------------------------------------------------------------------

async function captureScreenshot(
  page: Page,
  activityId: string,
  title: string,
): Promise<void> {
  try {
    const screenshot = await page.screenshot({ fullPage: false, type: "png" });
    addArtifact(activityId, {
      type: "screenshot",
      title,
      content: screenshot.toString("base64"),
      mimeType: "image/png",
    });
  } catch (err) {
    console.warn(`[QAEngager] Screenshot failed: ${err}`);
  }
}

// ---------------------------------------------------------------------------
// Login helper
// ---------------------------------------------------------------------------

async function loginIfNeeded(
  page: Page,
  channel: ChannelConfig,
  loginUrl: string,
  usernameSelector: string,
  passwordSelector: string,
  submitSelector: string,
): Promise<void> {
  if (!channel.credentials?.username || !channel.credentials?.password) {
    console.log(`[QAEngager] No credentials for ${channel.name}, skipping login`);
    return;
  }

  await page.goto(loginUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await page.waitForTimeout(2000);

  const usernameField = page.locator(usernameSelector).first();
  if (!(await usernameField.isVisible({ timeout: 3000 }).catch(() => false))) {
    console.log(`[QAEngager] Already logged in to ${channel.name}`);
    return;
  }

  await usernameField.fill(channel.credentials.username);
  await page.waitForTimeout(500);

  const passwordField = page.locator(passwordSelector).first();
  await passwordField.fill(channel.credentials.password);
  await page.waitForTimeout(500);

  await page.locator(submitSelector).first().click();
  await page.waitForTimeout(5000);
}

// ---------------------------------------------------------------------------
// Platform-specific handlers
// ---------------------------------------------------------------------------

async function engageOnReddit(
  page: Page,
  params: QAEngageParams,
  activityId: string,
): Promise<PostResult> {
  const { channel, keyword, answerContent } = params;

  // Login
  await loginIfNeeded(
    page,
    channel,
    "https://www.reddit.com/login",
    '#loginUsername, input[name="username"]',
    '#loginPassword, input[name="password"]',
    'button[type="submit"]',
  );

  // Search for keyword
  const searchUrl = `https://www.reddit.com/search/?q=${encodeURIComponent(keyword)}&type=link&sort=new`;
  await page.goto(searchUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await page.waitForTimeout(3000);

  await captureScreenshot(page, activityId, `Reddit検索: "${keyword}"`);

  // Find the first post to comment on
  const postLinks = page.locator('a[data-click-id="body"]').first();
  if (await postLinks.isVisible({ timeout: 5000 }).catch(() => false)) {
    await postLinks.click();
    await page.waitForTimeout(3000);

    // Find comment box
    const commentBox = page.locator('[contenteditable="true"], textarea[placeholder*="comment"], [name="comment"]').first();
    if (await commentBox.isVisible({ timeout: 5000 }).catch(() => false)) {
      await commentBox.click();
      await page.keyboard.type(answerContent, { delay: 10 });
      await page.waitForTimeout(1000);

      await captureScreenshot(page, activityId, `Reddit回答プレビュー`);

      // Submit comment
      const submitBtn = page.locator('button:has-text("Comment"), button:has-text("Reply")').first();
      if (await submitBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
        await submitBtn.click();
        await page.waitForTimeout(5000);
      }

      await captureScreenshot(page, activityId, `Reddit回答投稿完了`);

      return {
        success: true,
        postUrl: page.url(),
        channel: "reddit",
        action: "post_comment",
      };
    }
  }

  return {
    success: false,
    error: "No suitable post found to comment on",
    channel: "reddit",
    action: "post_comment",
  };
}

async function engageOnQuora(
  page: Page,
  params: QAEngageParams,
  activityId: string,
): Promise<PostResult> {
  const { channel, keyword, answerContent } = params;

  // Login
  await loginIfNeeded(
    page,
    channel,
    "https://www.quora.com/",
    'input[placeholder*="Email"], input[name="email"]',
    'input[type="password"]',
    'button:has-text("Login"), button[type="submit"]',
  );

  // Search for keyword
  const searchUrl = `https://www.quora.com/search?q=${encodeURIComponent(keyword)}`;
  await page.goto(searchUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await page.waitForTimeout(3000);

  await captureScreenshot(page, activityId, `Quora検索: "${keyword}"`);

  // Find an unanswered or recent question
  const questionLinks = page.locator('a[href*="/unanswered/"], .q-box a').first();
  if (await questionLinks.isVisible({ timeout: 5000 }).catch(() => false)) {
    await questionLinks.click();
    await page.waitForTimeout(3000);

    // Click "Answer" button
    const answerBtn = page.locator('button:has-text("Answer"), button:has-text("回答")').first();
    if (await answerBtn.isVisible({ timeout: 5000 }).catch(() => false)) {
      await answerBtn.click();
      await page.waitForTimeout(2000);

      // Type answer
      const editor = page.locator('[contenteditable="true"]').first();
      if (await editor.isVisible({ timeout: 3000 }).catch(() => false)) {
        await editor.click();
        await page.keyboard.type(answerContent, { delay: 10 });
        await page.waitForTimeout(1000);

        await captureScreenshot(page, activityId, `Quora回答プレビュー`);

        // Submit
        const submitBtn = page.locator('button:has-text("Submit"), button:has-text("Post")').first();
        if (await submitBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
          await submitBtn.click();
          await page.waitForTimeout(5000);
        }

        await captureScreenshot(page, activityId, `Quora回答投稿完了`);

        return {
          success: true,
          postUrl: page.url(),
          channel: "quora",
          action: "answer_question",
        };
      }
    }
  }

  return {
    success: false,
    error: "No suitable question found to answer",
    channel: "quora",
    action: "answer_question",
  };
}

async function engageOnYahooChiebukuro(
  page: Page,
  params: QAEngageParams,
  activityId: string,
): Promise<PostResult> {
  const { channel, keyword, answerContent } = params;

  // Login via Yahoo Japan
  if (channel.credentials?.username && channel.credentials?.password) {
    await page.goto("https://login.yahoo.co.jp/config/login", {
      waitUntil: "domcontentloaded",
      timeout: 30_000,
    });
    await page.waitForTimeout(2000);

    const usernameInput = page.locator('#username').first();
    if (await usernameInput.isVisible({ timeout: 3000 }).catch(() => false)) {
      await usernameInput.fill(channel.credentials.username);
      const nextBtn = page.locator('#btnNext').first();
      await nextBtn.click();
      await page.waitForTimeout(2000);

      const pwInput = page.locator('#passwd').first();
      if (await pwInput.isVisible({ timeout: 3000 }).catch(() => false)) {
        await pwInput.fill(channel.credentials.password);
        const loginBtn = page.locator('#btnSubmit').first();
        await loginBtn.click();
        await page.waitForTimeout(5000);
      }
    }
  }

  // Search on chiebukuro
  const searchUrl = `https://chiebukuro.yahoo.co.jp/search?p=${encodeURIComponent(keyword)}&flg=3&sort=1`;
  await page.goto(searchUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await page.waitForTimeout(3000);

  await captureScreenshot(page, activityId, `Yahoo!知恵袋検索: "${keyword}"`);

  // Find an open question (status: unanswered)
  const questionLink = page.locator('.ClapLi_titleArea a, a[href*="/question/"]').first();
  if (await questionLink.isVisible({ timeout: 5000 }).catch(() => false)) {
    await questionLink.click();
    await page.waitForTimeout(3000);

    // Click answer button
    const answerBtn = page.locator('a:has-text("回答する"), button:has-text("回答する")').first();
    if (await answerBtn.isVisible({ timeout: 5000 }).catch(() => false)) {
      await answerBtn.click();
      await page.waitForTimeout(2000);

      const textarea = page.locator('textarea[name="answer"], textarea').first();
      if (await textarea.isVisible({ timeout: 3000 }).catch(() => false)) {
        await textarea.fill(answerContent);
        await page.waitForTimeout(1000);

        await captureScreenshot(page, activityId, `Yahoo!知恵袋回答プレビュー`);

        const submitBtn = page.locator('button:has-text("回答する"), input[type="submit"]').first();
        if (await submitBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
          await submitBtn.click();
          await page.waitForTimeout(5000);
        }

        await captureScreenshot(page, activityId, `Yahoo!知恵袋回答投稿完了`);

        return {
          success: true,
          postUrl: page.url(),
          channel: "yahoo_chiebukuro",
          action: "answer_question",
        };
      }
    }
  }

  return {
    success: false,
    error: "No suitable question found to answer",
    channel: "yahoo_chiebukuro",
    action: "answer_question",
  };
}

async function engageOnZhihu(
  page: Page,
  params: QAEngageParams,
  activityId: string,
): Promise<PostResult> {
  const { channel, keyword, answerContent } = params;

  if (channel.credentials?.username && channel.credentials?.password) {
    await page.goto("https://www.zhihu.com/signin", {
      waitUntil: "domcontentloaded",
      timeout: 30_000,
    });
    await page.waitForTimeout(2000);

    const emailInput = page.locator('input[name="username"]').first();
    if (await emailInput.isVisible({ timeout: 3000 }).catch(() => false)) {
      await emailInput.fill(channel.credentials.username);
      const pwInput = page.locator('input[name="password"]').first();
      await pwInput.fill(channel.credentials.password);
      const loginBtn = page.locator('button:has-text("登录")').first();
      await loginBtn.click();
      await page.waitForTimeout(5000);
    }
  }

  const searchUrl = `https://www.zhihu.com/search?type=content&q=${encodeURIComponent(keyword)}`;
  await page.goto(searchUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  await page.waitForTimeout(3000);

  await captureScreenshot(page, activityId, `知乎検索: "${keyword}"`);

  const questionLink = page.locator('a[href*="/question/"]').first();
  if (await questionLink.isVisible({ timeout: 5000 }).catch(() => false)) {
    await questionLink.click();
    await page.waitForTimeout(3000);

    const writeAnswerBtn = page.locator('button:has-text("写回答")').first();
    if (await writeAnswerBtn.isVisible({ timeout: 5000 }).catch(() => false)) {
      await writeAnswerBtn.click();
      await page.waitForTimeout(2000);

      const editor = page.locator('[contenteditable="true"]').first();
      if (await editor.isVisible({ timeout: 3000 }).catch(() => false)) {
        await editor.click();
        await page.keyboard.type(answerContent, { delay: 10 });
        await page.waitForTimeout(1000);

        await captureScreenshot(page, activityId, `知乎回答プレビュー`);

        const submitBtn = page.locator('button:has-text("提交回答")').first();
        if (await submitBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
          await submitBtn.click();
          await page.waitForTimeout(5000);
        }

        await captureScreenshot(page, activityId, `知乎回答投稿完了`);

        return {
          success: true,
          postUrl: page.url(),
          channel: "zhihu",
          action: "answer_question",
        };
      }
    }
  }

  return {
    success: false,
    error: "No suitable question found to answer",
    channel: "zhihu",
    action: "answer_question",
  };
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

const QA_HANDLERS: Partial<
  Record<
    ChannelType,
    (page: Page, params: QAEngageParams, activityId: string) => Promise<PostResult>
  >
> = {
  reddit: engageOnReddit,
  quora: engageOnQuora,
  yahoo_chiebukuro: engageOnYahooChiebukuro,
  zhihu: engageOnZhihu,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function engageOnQA(params: QAEngageParams): Promise<PostResult> {
  const activity = startActivity({
    projectId: params.projectId,
    taskId: params.taskId,
    type: "social_posting",
    country: params.channel.regions[0] ?? "GLOBAL",
    language: params.channel.languages[0] ?? "en",
    method: "QAEngagement",
    description: `Q&A回答: ${params.channel.name} — キーワード "${params.keyword}"`,
  });

  const pool = getBrowserPool();

  try {
    const handler = QA_HANDLERS[params.channel.type];
    if (!handler) {
      const result: PostResult = {
        success: false,
        error: `Unsupported Q&A platform: ${params.channel.type}`,
        channel: params.channel.type,
        action: "answer_question",
      };
      failActivity(activity.id, result.error!);
      return result;
    }

    const result = await pool.withPage(
      async (page) => handler(page, params, activity.id),
      { country: params.channel.regions[0] },
    );

    addArtifact(activity.id, {
      type: "json",
      title: `Q&A回答結果: ${params.channel.name}`,
      content: JSON.stringify(result, null, 2),
    });

    if (result.success) {
      completeActivity(activity.id, {
        metrics: { answered: 1 },
        details: {
          postUrl: result.postUrl,
          channel: params.channel.type,
          keyword: params.keyword,
        },
      });
    } else {
      failActivity(activity.id, result.error ?? "No suitable question found");
    }

    return result;
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    failActivity(activity.id, errorMsg);
    return {
      success: false,
      error: errorMsg,
      channel: params.channel.type,
      action: "answer_question",
    };
  }
}
